model:
  num_problems : 1000
  num_agent_runs : 1000
  model_training_steps : 100
  history_len: 15
  epochs : 10
  lr : 0.01

  
problem : 'MNIST' #options:['MNIST', 'MathProblem']


policy:
  model: 'DQN' # options:['DQN', 'PPO']  info: DQN for hard method, PPO for soft method.
  exploration_fraction : 0.5
  optimization_mode : 'hard' # options:['soft', 'hard']

environment:
  reward_system : "lookahead" # options:['function', 'lookahead']  # info: Lookahead only for hard method.
  optimizer_storing_method : "state_dict" # options:['dict', optimizer_class']
