model:
  num_problems : 1000
  num_agent_runs : 1000
  model_training_steps : 50
  history_len: 5
  epochs : 10
  lr : 0.01


policy:
  model: 'DQN' # options:['DQN', 'PPO']
  exploration_fraction : 0.5
  
  
environment:
  reward_system : "lookahead" # options:['function', 'lookahead']
  optimizer_storing_method : "state_dict" # options:['state_dict','class_dict']