model:
  num_problems : 1000
  num_agent_runs : 100
  model_training_steps : 100
  history_len: 5
  epochs : 10
  lr : 0.01


policy:
  model: 'DQN' # options:['DQN', 'PPO']
  exploration_fraction : 0.5