model:
  num_problems : 100
  num_agent_runs : 100
  model_training_steps : 25
  history_len: 25
  epochs : 10
  lr : 0.01

  
problem : 'SquareProblem' #options:['MNIST', 'SquareProblem', 'AckleyProblem', 'MLPProblem']


policy:
  model: 'DQN' # options:['DQN', 'PPO']  info: DQN for hard method, PPO for soft method.
  exploration_fraction : 0.5
  optimization_mode : 'hard' # options:['soft', 'hard']

environment:
  reward_system : "function" # options:['function', 'lookahead']  # info: Lookahead only for hard method.
  optimizer_storing : "dict" # options:['dict', optimizer_class']