model:
  num_problems : 1000
  num_agent_runs : 1000
  model_training_steps : 100
  history_len: 25
  epochs : 10
  lr : 0.01
  optimizer_method : 'beta' #options: [beta, normal]


policy:
  model: 'DQN' # options:['DQN', 'PPO']
  exploration_fraction : 0.1 # only for DQN